// sigil-pruner.ts v0.2.0
// Auto-generated by Sigil — do not edit.
// Self-contained OpenCode plugin for server-side context pruning.
// NO npm imports — types are inlined, tool schemas use plain JSON Schema.

// ============================================================================
// Inlined types
// ============================================================================

interface MessageInfo {
  id: string
  role: "user" | "assistant"
  parts: Part[]
  metadata: {
    time: { created: number; completed?: number }
    error?: { name: string; data: { message: string } }
    sessionID: string
    tool: Record<
      string,
      {
        title: string
        snapshot?: string
        time: { start: number; end: number }
      }
    >
    assistant?: {
      system: string[]
      modelID: string
      providerID: string
      path: { cwd: string; root: string }
      cost: number
      summary?: boolean
      tokens: {
        input: number
        output: number
        reasoning: number
        cache: { read: number; write: number }
      }
    }
    snapshot?: string
  }
}

type Part =
  | { type: "text"; text: string }
  | { type: "reasoning"; text: string; providerMetadata?: Record<string, unknown> }
  | { type: "tool-invocation"; toolInvocation: ToolInvocation }
  | { type: "source-url"; sourceId: string; url: string; title?: string; providerMetadata?: Record<string, unknown> }
  | { type: "file"; mediaType: string; url: string; filename?: string }
  | { type: "step-start" }

type ToolInvocation =
  | { state: "call"; step?: number; toolCallId: string; toolName: string; args: unknown }
  | { state: "partial-call"; step?: number; toolCallId: string; toolName: string; args: unknown }
  | { state: "result"; step?: number; toolCallId: string; toolName: string; args: unknown; result: string }

interface MessageWithParts {
  info: MessageInfo
  parts: Part[]
}

// ============================================================================
// Config
// ============================================================================

interface PrunerConfig {
  enabled: boolean
  pluginApiVersion: number
  deterministic: {
    dedupEnabled: boolean
    pruneOldToolOutputs: boolean
    maxToolOutputMessages: number
    pruneErroredToolInputs: boolean
    erroredToolTurns: number
  }
  compress: {
    enabled: boolean
    mode: "range" | "message"
    protectedTools: string[]
  }
}

const DEFAULT_CONFIG: PrunerConfig = {
  enabled: true,
  pluginApiVersion: 1,
  deterministic: {
    dedupEnabled: true,
    pruneOldToolOutputs: true,
    maxToolOutputMessages: 20,
    pruneErroredToolInputs: true,
    erroredToolTurns: 4,
  },
  compress: {
    enabled: true,
    mode: "range",
    protectedTools: ["task", "skill", "todowrite", "todoread"],
  },
}

// ============================================================================
// Constants
// ============================================================================

const PRUNER_API_VERSION = 1
const PRUNER_CONFIG_PATH = ".opencode/sigil-pruner.json"
const PRUNER_HEARTBEAT_PATH = ".opencode/sigil-pruner.heartbeat"
const PRUNER_PLACEHOLDER_OUTPUT = "[Output pruned — was {tool}, ~{tokens} tokens]"
const PRUNER_PLACEHOLDER_SUPERSEDED = "[Output removed — superseded by newer call]"
const PRUNER_PLACEHOLDER_ERRORED_INPUT = "[input removed due to failed tool call]"
const COMPRESSED_BLOCK_HEADER = "[Compressed conversation section]"
const PRUNER_STATE_DIR = `${require("os").homedir()}/.local/share/opencode/storage/plugin/sigil-pruner`

// ============================================================================
// Per-session state
// ============================================================================

interface CompressionBlock {
  id: string
  anchorMessageId: string
  startMessageRef: string
  endMessageRef: string
  topic: string
  summary: string
  createdAtMs: number
}

interface PrunerStats {
  toolOutputsPruned: number
  toolInputsPruned: number
  messagesCompressed: number
  estimatedTokensSaved: number
}

interface SessionState {
  sessionId: string
  messageRefs: Map<string, string>
  compressionBlocks: CompressionBlock[]
  dedupSignatures: Map<string, string>
  messageTextCache: Map<string, string>
  stats: PrunerStats
  lastHeartbeatMs: number
}

// ============================================================================
// Plugin entry point
// ============================================================================

interface PluginInput {
  client: { session: { prompt: (params: any) => Promise<any> } }
  project: unknown
  directory: string
  worktree: string
  serverUrl: URL
  $: unknown
}

interface PluginResult {
  "experimental.chat.messages.transform"?: (
    input: {},
    output: { messages: MessageWithParts[] }
  ) => Promise<void>
  "experimental.chat.system.transform"?: (
    input: { sessionID?: string; model: unknown },
    output: { system: string[] }
  ) => Promise<void>
  "command.execute.before"?: (
    input: { command: string; sessionID: string; arguments: string },
    output: { parts: Part[] }
  ) => Promise<void>
  config?: (opencodeConfig: any) => Promise<void>
  tool?: Record<
    string,
    {
      description: string
      args: Record<string, unknown>
      execute: (args: unknown, context: any) => Promise<unknown>
    }
  >
  event?: (event: any) => Promise<void>
}

const server = async (ctx: PluginInput): Promise<PluginResult> => {
  const config = loadConfig()
  if (!config.enabled) return {}

  const state = createSessionState()
  const client = ctx.client

  try {
    return {
      "experimental.chat.messages.transform": createMessageTransformHandler(
        config,
        state,
        ctx.directory
      ),
      "experimental.chat.system.transform": createSystemTransformHandler(config),
      "command.execute.before": createCommandHandler(config, state),
      config: createConfigHook(config),
      tool: config.compress.enabled
        ? {
            compress: createCompressTool(config, state, client),
          }
        : undefined,
      event: createEventHandler(state),
    }
  } catch (e) {
    console.error("[sigil-pruner] Failed to register hooks:", e)
    return {}
  }
}

export default { server }

// ============================================================================
// Config loading
// ============================================================================

function loadConfig(): PrunerConfig {
  try {
    const fs = require("fs")
    const path = require("path")
    const configPath = path.join(process.cwd(), PRUNER_CONFIG_PATH)
    if (!fs.existsSync(configPath)) {
      return { ...DEFAULT_CONFIG }
    }
    const raw = fs.readFileSync(configPath, "utf-8")
    const parsed = JSON.parse(raw)
    if (parsed.pluginApiVersion !== PRUNER_API_VERSION) {
      console.warn(
        `[sigil-pruner] Config API version mismatch: expected ${PRUNER_API_VERSION}, got ${parsed.pluginApiVersion}. Disabling pruner.`
      )
      return { ...DEFAULT_CONFIG, enabled: false }
    }
    return { ...DEFAULT_CONFIG, ...parsed }
  } catch (e) {
    console.warn("[sigil-pruner] Failed to load config, using defaults:", e)
    return { ...DEFAULT_CONFIG }
  }
}

// ============================================================================
// Session state
// ============================================================================

function createSessionState(): SessionState {
  return {
    sessionId: "",
    messageRefs: new Map(),
    compressionBlocks: [],
    dedupSignatures: new Map(),
    messageTextCache: new Map(),
    stats: {
      toolOutputsPruned: 0,
      toolInputsPruned: 0,
      messagesCompressed: 0,
      estimatedTokensSaved: 0,
    },
    lastHeartbeatMs: 0,
  }
}

// ============================================================================
// messages.transform hook
// ============================================================================

function createMessageTransformHandler(
  config: PrunerConfig,
  state: SessionState,
  directory: string
): (input: {}, output: { messages: MessageWithParts[] }) => Promise<void> {
  return async (_input, output) => {
    const messages = output.messages
    if (!messages || messages.length === 0) return

    // Derive session id from first message if not set
    if (!state.sessionId && messages[0]?.info?.metadata?.sessionID) {
      state.sessionId = messages[0].info.metadata.sessionID
    }

    assignMessageRefs(state, messages)
    cacheMessages(state, messages)
    syncCompressionBlocks(state, messages)
    syncToolCache(state, messages)

    if (config.deterministic.dedupEnabled) {
      deduplicateToolCalls(state, messages)
    }

    if (config.deterministic.pruneOldToolOutputs) {
      pruneOldToolOutputs(state, messages, config.deterministic.maxToolOutputMessages, config)
    }

    if (config.deterministic.pruneErroredToolInputs) {
      pruneErroredToolInputs(state, messages, config.deterministic.erroredToolTurns)
    }

    applyCompressionBlocks(state, messages)

    // Write heartbeat (JSON format — Kotlin PrunerHeartbeatReader parses tokensSaved)
    state.lastHeartbeatMs = Date.now()
    writeHeartbeat(state.lastHeartbeatMs, directory, state.stats)
  }
}

// ============================================================================
// system.transform hook
// ============================================================================

function createSystemTransformHandler(
  config: PrunerConfig
): (input: { sessionID?: string; model: unknown }, output: { system: string[] }) => Promise<void> {
  return async (_input, output) => {
    if (!config.enabled) return
    output.system.push(
      "Note: A context pruner is active. Old tool outputs may be replaced with placeholders. Use the compress tool to summarize completed conversation sections."
    )
  }
}

// ============================================================================
// command.execute.before hook
// ============================================================================

function createCommandHandler(
  config: PrunerConfig,
  state: SessionState
): (
  input: { command: string; sessionID: string; arguments: string },
  output: { parts: Part[] }
) => Promise<void> {
  return async (input, output) => {
    if (input.command !== "sigil-prune") return

    const args = input.arguments.trim()

    if (args === "stats") {
      output.parts = [{ type: "text", text: formatStats(state.stats) }]
      return
    }

    if (args === "sweep" || args.startsWith("sweep")) {
      const parts = args.split(/\s+/)
      const count = parts.length > 1 ? parseInt(parts[1], 10) : 0
      const result = performSweep(state, count)
      output.parts = [{ type: "text", text: result }]
      return
    }

    if (args === "compress" || args.startsWith("compress ")) {
      const focusArg = args.startsWith("compress ") ? args.slice("compress ".length).trim() : ""

      const modeInstruction = config.compress.mode === "message"
        ? 'Use the `compress` tool with individual message refs:\n```json\n{"topic": "Large output", "content": [{"messageId": "m0005"}, {"messageId": "m0012"}]}\n```'
        : 'Use the `compress` tool with a topic and message ranges:\n```json\n{"topic": "File exploration", "content": [{"startId": "m0003", "endId": "m0010"}]}\n```'

      if (focusArg) {
        // Sanitize focusArg: strip newlines and limit length to prevent prompt injection.
        // The summarizer agent has all tools disabled, but unsanitized input could still
        // produce misleading summaries or leak system prompt content.
        const safeFocus = focusArg.replace(/[\n\r]/g, " ").slice(0, 200)
        // User provided a focus — instruct the LLM to compress with this focus
        output.parts = [
          {
            type: "text",
            text: `Compress completed conversation sections, focusing on: ${safeFocus}. ${modeInstruction}\n\nPrioritize preserving information related to "${safeFocus}".`,
          },
        ]
      } else {
        // No focus — show generic instructions
        output.parts = [
          {
            type: "text",
            text: `To compress a conversation section, ${modeInstruction}`,
          },
        ]
      }
      return
    }

    // Default help
    output.parts = [
      {
        type: "text",
        text: [
          "**sigil-prune** — Context pruner commands:",
          "",
          "`sigil-prune stats` — Show pruning statistics",
          "`sigil-prune sweep` — Prune all eligible tool outputs now",
          "`sigil-prune sweep N` — Prune tool outputs older than N messages",
          "`sigil-prune compress [focus]` — Instructions for compressing conversation sections (range or message mode), optionally with a focus area",
        ].join("\n"),
      },
    ]
  }
}

// ============================================================================
// config hook
// ============================================================================

function createConfigHook(
  config: PrunerConfig
): (opencodeConfig: any) => Promise<void> {
  return async (opencodeConfig) => {
    // Register /sigil-prune command
    opencodeConfig.command ??= {}
    opencodeConfig.command["sigil-prune"] = {
      template: "sigil-prune $ARGUMENTS",
      description: "Context pruner: stats, sweep, compress",
    }

    // Register sigil-summarizer sub-agent (no tools → recursion guard)
    opencodeConfig.agent ??= {}
    opencodeConfig.agent["sigil-summarizer"] = {
      mode: "subagent",
      prompt:
        "You are a technical summarizer. Produce concise summaries preserving key decisions, file paths, and code snippets. Do not use any tools.",
      tools: {
        write: false,
        edit: false,
        bash: false,
        read: false,
        task: false,
        skill: false,
        todowrite: false,
        todoread: false,
        glob: false,
        grep: false,
      },
    }
  }
}

// ============================================================================
// compress tool
// ============================================================================

function createCompressTool(
  config: PrunerConfig,
  state: SessionState,
  client: PluginInput["client"]
): {
  description: string
  args: Record<string, unknown>
  execute: (args: unknown, context: any) => Promise<unknown>
} {
  return {
    description:
      config.compress.mode === "message"
        ? "Summarize individual conversation messages to free up context. Pass specific message refs in content[].messageId. Each message gets its own independent summary. Useful for compressing large individual tool outputs without losing surrounding context."
        : "Summarize old conversation messages to free up context. Call this when a task section is complete and the verbatim conversation is no longer needed. The tool generates a high-quality summary via a dedicated sub-agent.",
    args: {
      topic: { type: "string", description: "Short label (3-5 words) for the compressed section" },
      content: {
        type: "array",
        description: "One or more ranges (range mode) or individual messages (message mode) to compress",
        items: {
          type: "object",
          properties: {
            startId: {
              type: "string",
              description: "Message ref (m0001) or block ref (b1) marking range start (range mode only)",
            },
            endId: {
              type: "string",
              description: "Message ref or block ref marking range end (range mode only)",
            },
            messageId: {
              type: "string",
              description: "Single message ref to compress (message mode only)",
            },
          },
        },
      },
    },
    async execute(args: unknown, context: any) {
      const { topic, content } = args as {
        topic: string
        content: Array<{ startId?: string; endId?: string; messageId?: string }>
      }
      try {
        context.metadata({ title: `Compressing: ${topic}` })
      } catch {
        // metadata() may not exist in all plugin contexts
      }

      const summaries: string[] = []
      for (const range of content) {
        try {
          let rangeText: string
          let startRef: string
          let endRef: string

          if (range.messageId) {
            // Message mode: compress a single message
            rangeText = extractRangeText(state, range.messageId, range.messageId)
            startRef = range.messageId
            endRef = range.messageId
          } else if (range.startId && range.endId) {
            // Range mode: compress a span
            rangeText = extractRangeText(state, range.startId, range.endId)
            startRef = range.startId
            endRef = range.endId
          } else {
            console.warn("[sigil-pruner] Invalid compress entry: needs either {startId, endId} or {messageId}")
            summaries.push(`[Invalid entry: ${JSON.stringify(range)}]`)
            continue
          }

          const summaryResponse = await client.session.prompt({
            sessionID: context.sessionID,
            parts: [
              {
                type: "text",
                text: `Summarize this conversation section concisely, preserving key decisions, file paths, and code snippets:\n\n${rangeText}`,
              },
            ],
            agent: "sigil-summarizer",
            noReply: true,
          })

          const summary = extractSummaryText(summaryResponse)
          const protectedOutputs = extractProtectedToolOutputs(state, startRef, endRef, config)
          const fullSummary = protectedOutputs ? summary + protectedOutputs : summary
          summaries.push(fullSummary)
          createCompressionBlock(state, startRef, endRef, topic, fullSummary)
        } catch (e) {
          console.error("[sigil-pruner] Failed to compress range:", e)
          summaries.push(`[Compression failed for ${JSON.stringify(range)}]`)
        }
      }

      state.stats.messagesCompressed += content.length
      await saveSessionState(state)

      return `Compressed ${content.length} message range(s) into [Compressed conversation section].`
    },
  }
}

// ============================================================================
// event hook
// ============================================================================

function createEventHandler(
  state: SessionState
): (event: any) => Promise<void> {
  return async (event: any) => {
    if (!event) return
    console.debug("[sigil-pruner] Event:", JSON.stringify(event)?.slice(0, 200))
  }
}

// ============================================================================
// Pruning logic: assignMessageRefs
// ============================================================================

function assignMessageRefs(state: SessionState, messages: MessageWithParts[]) {
  let counter = state.messageRefs.size
  for (const msg of messages) {
    if (!state.messageRefs.has(msg.info.id)) {
      counter++
      state.messageRefs.set(msg.info.id, `m${String(counter).padStart(4, "0")}`)
    }
  }
}

// ============================================================================
// Pruning logic: flattenMessageText
// ============================================================================

function flattenMessageText(msg: MessageWithParts): string {
  const segments: string[] = []
  for (const part of msg.parts) {
    if (part.type === "text" && part.text) {
      segments.push(part.text)
    } else if (part.type === "reasoning" && part.text) {
      segments.push(`[reasoning] ${part.text}`)
    } else if (part.type === "tool-invocation" && part.toolInvocation.state === "result") {
      const ti = part.toolInvocation
      const argsStr = JSON.stringify(ti.args ?? {})
      const resultStr = typeof ti.result === "string"
        ? (ti.result.length > 2000 ? ti.result.slice(0, 2000) + "…" : ti.result)
        : String(ti.result)
      segments.push(`[tool: ${ti.toolName}] args: ${argsStr} result: ${resultStr}`)
    }
  }
  return segments.join("\n")
}

// ============================================================================
// Pruning logic: cacheMessages (snapshots text BEFORE pruning)
// ============================================================================

function cacheMessages(state: SessionState, messages: MessageWithParts[]) {
  for (const msg of messages) {
    // Only cache if not already present (avoid overwriting with pruned content)
    if (!state.messageTextCache.has(msg.info.id)) {
      state.messageTextCache.set(msg.info.id, flattenMessageText(msg))
    }
  }
}

// ============================================================================
// Pruning logic: syncCompressionBlocks
// ============================================================================

function syncCompressionBlocks(state: SessionState, messages: MessageWithParts[]) {
  const existingIds = new Set(messages.map((m) => m.info.id))
  state.compressionBlocks = state.compressionBlocks.filter((block) => {
    const anchorExists = existingIds.has(block.anchorMessageId)
    if (!anchorExists) {
      console.debug(
        `[sigil-pruner] Removing compression block ${block.id}: anchor ${block.anchorMessageId} no longer exists`
      )
    }
    return anchorExists
  })
}

// ============================================================================
// Pruning logic: canonicalizeArgs
// ============================================================================

function canonicalizeArgs(args: unknown): unknown {
  if (args === null || args === undefined) return args
  if (typeof args !== "object") return args
  if (Array.isArray(args)) return args.map(canonicalizeArgs)
  const sorted: Record<string, unknown> = {}
  for (const key of Object.keys(args as Record<string, unknown>).sort()) {
    sorted[key] = canonicalizeArgs((args as Record<string, unknown>)[key])
  }
  return sorted
}

// ============================================================================
// Pruning logic: syncToolCache
// ============================================================================

function syncToolCache(state: SessionState, messages: MessageWithParts[]) {
  state.dedupSignatures.clear()
  for (const msg of messages) {
    for (const part of msg.parts) {
      if (part.type !== "tool-invocation") continue
      const ti = part.toolInvocation
      if (ti.state !== "result") continue
      const sig = `${ti.toolName}::${JSON.stringify(canonicalizeArgs(ti.args))}`
      state.dedupSignatures.set(sig, ti.toolCallId)
    }
  }
}

// ============================================================================
// Pruning logic: deduplicateToolCalls
// ============================================================================

function deduplicateToolCalls(state: SessionState, messages: MessageWithParts[]) {
  const seen = new Map<string, string>() // signature → toolCallId (first seen)

  for (const msg of messages) {
    for (let i = 0; i < msg.parts.length; i++) {
      const part = msg.parts[i]
      if (part.type !== "tool-invocation") continue
      const ti = part.toolInvocation
      if (ti.state !== "result") continue

      const sig = `${ti.toolName}::${JSON.stringify(canonicalizeArgs(ti.args))}`
      const existing = seen.get(sig)

      if (existing) {
        // This is a duplicate — replace with superseded placeholder
        msg.parts[i] = {
          type: "tool-invocation",
          toolInvocation: {
            ...ti,
            result: PRUNER_PLACEHOLDER_SUPERSEDED,
          },
        }
        state.stats.toolOutputsPruned++
        console.debug(
          `[sigil-pruner] Deduped tool call ${ti.toolName} (${ti.toolCallId}) — superseded by ${existing}`
        )
      } else {
        seen.set(sig, ti.toolCallId)
      }
    }
  }
}

// ============================================================================
// Pruning logic: classifyTool
// ============================================================================

function classifyTool(toolName: string): "read" | "search" | "ephemeral" | "mutation" {
  const lower = toolName.toLowerCase()
  if (["read", "read_file", "cat", "head", "tail"].includes(lower)) return "read"
  if (["grep", "glob", "find", "search", "rg"].includes(lower)) return "search"
  if (["write", "edit", "patch", "delete", "mv", "mkdir"].includes(lower)) return "mutation"
  return "ephemeral"
}

// ============================================================================
// Pruning logic: extractPathFromArgs
// ============================================================================

function extractPathFromArgs(args: unknown): string | null {
  if (typeof args !== "object" || args === null) return null
  const obj = args as Record<string, unknown>
  for (const key of ["path", "file_path", "filePath", "file", "filename"]) {
    if (typeof obj[key] === "string" && obj[key]) return obj[key] as string
  }
  return null
}

// ============================================================================
// Pruning logic: extractQueryFromArgs (Phase 3)
// ============================================================================

function extractQueryFromArgs(args: unknown): string | null {
  if (typeof args !== "object" || args === null) return null
  const obj = args as Record<string, unknown>
  for (const key of ["query", "pattern", "search", "regex", "glob"]) {
    if (typeof obj[key] === "string" && obj[key]) return obj[key] as string
  }
  return null
}

// ============================================================================
// Pruning logic: isSuperseded
// ============================================================================

function isSuperseded(
  messages: MessageWithParts[],
  idx: number,
  ti: ToolInvocation
): boolean {
  const category = classifyTool(ti.toolName)
  const argsPath = extractPathFromArgs(ti.args)

  for (let j = idx + 1; j < messages.length; j++) {
    for (const part of messages[j].parts) {
      if (part.type !== "tool-invocation") continue
      const later = part.toolInvocation
      if (later.state !== "result") continue
      if (later.toolName !== ti.toolName) continue

      if (category === "read") {
        // Superseded if a later read targets the same path
        const laterPath = extractPathFromArgs(later.args)
        if (laterPath && argsPath && laterPath === argsPath) return true
      } else if (category === "search") {
        // Superseded if a later search has the same query/pattern
        const myQuery = extractQueryFromArgs(ti.args)
        const laterQuery = extractQueryFromArgs(later.args)
        if (myQuery && laterQuery && myQuery === laterQuery) return true
      }
    }
  }
  return false
}

// ============================================================================
// Pruning logic: wasFileModifiedSince
// ============================================================================

function wasFileModifiedSince(
  messages: MessageWithParts[],
  idx: number,
  filePath: string | null
): boolean {
  if (!filePath) return false
  for (let j = idx + 1; j < messages.length; j++) {
    for (const part of messages[j].parts) {
      if (part.type !== "tool-invocation") continue
      const later = part.toolInvocation
      if (later.state !== "result") continue
      if (classifyTool(later.toolName) !== "mutation") continue
      const laterPath = extractPathFromArgs(later.args)
      if (laterPath && laterPath === filePath) return true
    }
  }
  return false
}

// ============================================================================
// Pruning logic: isReferencedLater
// ============================================================================

function isReferencedLater(
  messages: MessageWithParts[],
  idx: number,
  ti: ToolInvocation
): boolean {
  const resultStr = typeof ti.result === "string" ? ti.result : ""
  const filePath = extractPathFromArgs(ti.args)

  // Use the first 80 chars of result or the file path as a reference fingerprint
  const fingerprint = resultStr.length > 0 ? resultStr.slice(0, 80) : (filePath ?? "")
  if (!fingerprint) return false

  for (let j = idx + 1; j < messages.length; j++) {
    const msg = messages[j]
    if (msg.info.role !== "assistant") continue
    for (const part of msg.parts) {
      if (part.type !== "text" || !part.text) continue
      if (part.text.includes(fingerprint)) return true
    }
  }
  return false
}

// ============================================================================
// Pruning logic: buildRichPlaceholder (Phase 3)
// ============================================================================

function buildRichPlaceholder(ti: ToolInvocation, category: string): string {
  const estimatedTokens = Math.ceil((typeof ti.result === "string" ? ti.result.length : 0) / 4)
  const path = extractPathFromArgs(ti.args)
  const query = extractQueryFromArgs(ti.args)

  const parts: string[] = [`[Output pruned — was ${ti.toolName}, ~${estimatedTokens} tokens]`]

  if (path) parts.push(`Path: ${path}`)
  if (query) parts.push(`Query: ${query}`)

  // Include a short excerpt for read/search tools (first 200 chars of result)
  if (category === "read" || category === "search") {
    const result = typeof ti.result === "string" ? ti.result : ""
    if (result.length > 0) {
      const excerpt = result.slice(0, 200).replace(/\n/g, " ")
      parts.push(`Excerpt: ${excerpt}${result.length > 200 ? "…" : ""}`)
    }
  }

  return parts.join(" | ")
}

// ============================================================================
// Pruning logic: pruneOldToolOutputs
// ============================================================================

function pruneOldToolOutputs(
  state: SessionState,
  messages: MessageWithParts[],
  maxAge: number,
  config: PrunerConfig
) {
  for (let idx = 0; idx < messages.length; idx++) {
    const msg = messages[idx]
    const ageFromEnd = messages.length - idx

    // Only prune messages older than maxAge
    if (ageFromEnd <= maxAge) continue

    // Don't prune protected messages (e.g., summaries or compressed blocks)
    const isCompressed = msg.parts.some(
      (p) => p.type === "text" && p.text.startsWith(COMPRESSED_BLOCK_HEADER)
    )
    if (isCompressed) continue

    for (let pi = 0; pi < msg.parts.length; pi++) {
      const part = msg.parts[pi]
      if (part.type !== "tool-invocation") continue
      const ti = part.toolInvocation
      if (ti.state !== "result") continue

      // Don't prune protected tools
      if (config.compress.protectedTools.includes(ti.toolName)) continue

      const resultLen = typeof ti.result === "string" ? ti.result.length : 0
      if (resultLen === 0) continue

      // Idempotency: skip already-pruned results
      if (typeof ti.result === "string" && ti.result.startsWith("[Output pruned")) continue
      if (ti.result === PRUNER_PLACEHOLDER_SUPERSEDED) continue

      const category = classifyTool(ti.toolName)
      let placeholder: string | null = null

      if (category === "mutation") {
        // Short confirmations, safe to prune aggressively
        placeholder = buildRichPlaceholder(ti, category)
      } else if (category === "read") {
        if (isSuperseded(messages, idx, ti)) {
          placeholder = PRUNER_PLACEHOLDER_SUPERSEDED
        } else if (wasFileModifiedSince(messages, idx, extractPathFromArgs(ti.args))) {
          const path = extractPathFromArgs(ti.args)
          placeholder = `[Output pruned — file modified since read: ${path}]`
        } else if (isReferencedLater(messages, idx, ti)) {
          continue // KEEP — don't prune
        } else {
          placeholder = buildRichPlaceholder(ti, category)
        }
      } else if (category === "search") {
        if (isSuperseded(messages, idx, ti)) {
          placeholder = PRUNER_PLACEHOLDER_SUPERSEDED
        } else if (isReferencedLater(messages, idx, ti)) {
          continue // KEEP — don't prune
        } else {
          placeholder = buildRichPlaceholder(ti, category)
        }
      } else {
        // ephemeral: command/web output — always safe to prune if old
        placeholder = buildRichPlaceholder(ti, category)
      }

      if (placeholder !== null) {
        const estimatedTokens = Math.ceil(resultLen / 4)
        msg.parts[pi] = {
          type: "tool-invocation",
          toolInvocation: {
            ...ti,
            result: placeholder,
          },
        }
        state.stats.toolOutputsPruned++
        state.stats.estimatedTokensSaved += estimatedTokens
      }
    }
  }
}

// ============================================================================
// Pruning logic: pruneErroredToolInputs
// ============================================================================

function pruneErroredToolInputs(
  state: SessionState,
  messages: MessageWithParts[],
  turns: number
) {
  for (let idx = 0; idx < messages.length; idx++) {
    const msg = messages[idx]
    if (!msg.info.metadata.error) continue

    // Count how many messages have passed since this errored message
    const messagesSince = messages.length - idx - 1
    if (messagesSince <= turns) continue

    // Find tool-invocation "call" parts in this message and replace args
    for (let pi = 0; pi < msg.parts.length; pi++) {
      const part = msg.parts[pi]
      if (part.type !== "tool-invocation") continue
      const ti = part.toolInvocation
      if (ti.state !== "call" && ti.state !== "partial-call") continue

      // Replace string values in args with placeholder
      const sanitizedArgs = sanitizeStringValuesInArgs(ti.args)

      msg.parts[pi] = {
        type: "tool-invocation",
        toolInvocation: {
          ...ti,
          args: sanitizedArgs,
        },
      }
      state.stats.toolInputsPruned++
    }

    // Preserve error message — do NOT remove metadata.error
  }
}

function sanitizeStringValuesInArgs(args: unknown): unknown {
  if (typeof args === "string") return PRUNER_PLACEHOLDER_ERRORED_INPUT
  if (typeof args !== "object" || args === null) return args

  if (Array.isArray(args)) {
    return args.map((item) => {
      if (typeof item === "string") return PRUNER_PLACEHOLDER_ERRORED_INPUT
      return item
    })
  }

  const result: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(args as Record<string, unknown>)) {
    if (typeof value === "string") {
      result[key] = PRUNER_PLACEHOLDER_ERRORED_INPUT
    } else {
      result[key] = value
    }
  }
  return result
}

// ============================================================================
// Pruning logic: applyCompressionBlocks
// ============================================================================

function applyCompressionBlocks(state: SessionState, messages: MessageWithParts[]) {
  if (state.compressionBlocks.length === 0) return

  // Build a ref → message index lookup
  const refToIndex = new Map<string, number>()
  for (let i = 0; i < messages.length; i++) {
    const ref = state.messageRefs.get(messages[i].info.id)
    if (ref) refToIndex.set(ref, i)
  }

  // Collect message IDs to remove and positions to insert
  const idsToRemove = new Set<string>()
  const insertions: Array<{ afterIndex: number; block: CompressionBlock }> = []

  for (const block of state.compressionBlocks) {
    const startIdx = refToIndex.get(block.startMessageRef)
    const endIdx = refToIndex.get(block.endMessageRef)
    const anchorIdx = refToIndex.get(state.messageRefs.get(block.anchorMessageId) ?? "")

    if (startIdx === undefined || endIdx === undefined || anchorIdx === undefined) continue

    // Mark messages in range for removal (keep anchor)
    for (let i = Math.min(startIdx, endIdx); i <= Math.max(startIdx, endIdx); i++) {
      if (i !== anchorIdx) {
        // Estimate tokens saved by removing this message
        const msgId = messages[i].info.id
        const cachedText = state.messageTextCache.get(msgId)
        if (cachedText) {
          state.stats.estimatedTokensSaved += Math.ceil(cachedText.length / 4)
        }
        idsToRemove.add(msgId)
      }
    }

    insertions.push({ afterIndex: anchorIdx, block })
  }

  if (idsToRemove.size === 0) return

  // Remove messages outside the range
  const filtered = messages.filter((m) => !idsToRemove.has(m.info.id))

  // Insert compressed blocks at anchor positions
  // We need to insert in reverse order to maintain correct indices
  insertions.sort((a, b) => b.afterIndex - a.afterIndex)

  for (const { afterIndex, block } of insertions) {
    // Find the anchor message in filtered list
    const anchorRef = state.messageRefs.get(block.anchorMessageId)
    const anchorFilteredIdx = filtered.findIndex(
      (m) => state.messageRefs.get(m.info.id) === anchorRef
    )

    if (anchorFilteredIdx === -1) continue

    // Replace the anchor message's parts with the compressed block
    const compressedPart: Part = {
      type: "text",
      text: `${COMPRESSED_BLOCK_HEADER}\n${block.summary}\n<sigil-block-id>${block.id}</sigil-block-id>`,
    }

    // Replace first part of anchor message with compressed block
    if (filtered[anchorFilteredIdx].parts.length > 0) {
      filtered[anchorFilteredIdx].parts = [compressedPart]
    } else {
      filtered[anchorFilteredIdx].parts.push(compressedPart)
    }

    // Subtract the summary's token cost from savings (the summary itself consumes context)
    const summaryTokens = Math.ceil(block.summary.length / 4)
    state.stats.estimatedTokensSaved = Math.max(0, state.stats.estimatedTokensSaved - summaryTokens)
  }

  // Replace the original array contents
  messages.length = 0
  messages.push(...filtered)
}

// ============================================================================
// Sweep (manual trigger)
// ============================================================================

function performSweep(state: SessionState, maxAge?: number): string {
  const age = maxAge && maxAge > 0 ? maxAge : 0
  const before = { ...state.stats }
  const beforeSaved = state.stats.estimatedTokensSaved

  // Sweep is triggered externally — we log the intent
  // Actual pruning happens on next messages.transform call
  return [
    `**sigil-prune sweep** triggered.`,
    `Tool outputs pruned so far: ${state.stats.toolOutputsPruned}`,
    `Tool inputs pruned so far: ${state.stats.toolInputsPruned}`,
    `Messages compressed so far: ${state.stats.messagesCompressed}`,
    `Estimated tokens saved: ${state.stats.estimatedTokensSaved}`,
    "",
    age > 0
      ? `Sweeping tool outputs older than ${age} messages.`
      : "Sweeping all eligible tool outputs.",
    "Pruning will apply on the next LLM call.",
  ].join("\n")
}

// ============================================================================
// extractRangeText — extract text from a message range
// ============================================================================

function extractRangeText(
  state: SessionState,
  startId: string,
  endId: string
): string {
  // Find indices in the stored message list using ref order
  const entries = Array.from(state.messageRefs.entries())
  const startIdx = entries.findIndex(([, ref]) => ref === startId)
  const endIdx = entries.findIndex(([, ref]) => ref === endId)

  if (startIdx === -1 && endIdx === -1) {
    return `[Range ${startId}..${endId} not found in message refs]`
  }

  const lo = Math.min(startIdx >= 0 ? startIdx : 0, endIdx >= 0 ? endIdx : entries.length - 1)
  const hi = Math.max(startIdx >= 0 ? startIdx : 0, endIdx >= 0 ? endIdx : entries.length - 1)

  // Collect message IDs in range and look up cached text
  const textChunks: string[] = []
  for (let i = lo; i <= hi; i++) {
    const [msgId] = entries[i]
    const cachedText = state.messageTextCache.get(msgId)
    if (cachedText) {
      textChunks.push(cachedText)
    } else {
      textChunks.push(`[Message ${msgId} — not in cache]`)
    }
  }

  return textChunks.join("\n\n")
}

// ============================================================================
// extractProtectedToolOutputs — append protected tool outputs to summary
// ============================================================================

function extractProtectedToolOutputs(
  state: SessionState,
  startId: string,
  endId: string,
  config: PrunerConfig
): string {
  // Build ref → messageId lookup
  const refToId = new Map<string, string>()
  for (const [id, ref] of state.messageRefs) {
    refToId.set(ref, id)
  }

  const entries = Array.from(state.messageRefs.entries())
  const startIdx = entries.findIndex(([, ref]) => ref === startId)
  const endIdx = entries.findIndex(([, ref]) => ref === endId)

  if (startIdx === -1 || endIdx === -1) return ""

  const lo = Math.min(startIdx, endIdx)
  const hi = Math.max(startIdx, endIdx)

  const protectedOutputs: string[] = []
  for (let i = lo; i <= hi; i++) {
    const msgId = entries[i][0]
    const cachedText = state.messageTextCache.get(msgId)
    if (!cachedText) continue

    // Check if this message's text contains protected tool outputs
    // We look for tool invocations with protected tool names in the original messages
    // Since messageTextCache has flattened text, we search for tool markers
    for (const toolName of config.compress.protectedTools) {
      const marker = `[tool: ${toolName}]`
      if (cachedText.includes(marker)) {
        // Extract the tool output section (from marker to next marker or end)
        const markerIdx = cachedText.indexOf(marker)
        const nextMarkerIdx = cachedText.indexOf("[tool:", markerIdx + 1)
        const sectionEnd = nextMarkerIdx === -1 ? cachedText.length : nextMarkerIdx
        const section = cachedText.slice(markerIdx, sectionEnd)
        if (section.length > 0 && !protectedOutputs.includes(section)) {
          protectedOutputs.push(section)
        }
      }
    }
  }

  if (protectedOutputs.length === 0) return ""
  return "\n\n--- Protected tool outputs preserved ---\n" + protectedOutputs.join("\n\n")
}

// ============================================================================
// Compression block creation
// ============================================================================

function createCompressionBlock(
  state: SessionState,
  startRef: string,
  endRef: string,
  topic: string,
  summary: string
) {
  const anchorRef = startRef
  // Resolve anchor message ID
  let anchorMessageId = ""
  for (const [id, ref] of state.messageRefs) {
    if (ref === anchorRef) {
      anchorMessageId = id
      break
    }
  }

  const blockId = `b${state.compressionBlocks.length + 1}`
  const block: CompressionBlock = {
    id: blockId,
    anchorMessageId,
    startMessageRef: startRef,
    endMessageRef: endRef,
    topic,
    summary,
    createdAtMs: Date.now(),
  }
  state.compressionBlocks.push(block)
  console.debug(`[sigil-pruner] Created compression block ${blockId}: ${topic}`)
}

// ============================================================================
// Save / load session state
// ============================================================================

async function saveSessionState(state: SessionState): Promise<void> {
  try {
    const fs = require("fs")
    const path = require("path")
    const os = require("os")

    const dir = PRUNER_STATE_DIR
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true })
    }

    const filePath = path.join(dir, `${(state.sessionId || "unknown").replace(/[^a-zA-Z0-9_-]/g, '_')}.json`)
    const data = {
      sessionId: state.sessionId,
      compressionBlocks: state.compressionBlocks,
      stats: state.stats,
      lastHeartbeatMs: state.lastHeartbeatMs,
    }
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2))
  } catch (e) {
    console.warn("[sigil-pruner] Failed to save session state:", e)
  }
}

// ============================================================================
// Heartbeat
// ============================================================================

function writeHeartbeat(timestampMs: number, directory: string, stats: PrunerStats): void {
  try {
    const fs = require("fs")
    const path = require("path")
    const heartbeatPath = path.join(directory, PRUNER_HEARTBEAT_PATH)
    const payload = JSON.stringify({
      timestamp: timestampMs,
      tokensSaved: stats.estimatedTokensSaved,
      outputsPruned: stats.toolOutputsPruned,
      inputsPruned: stats.toolInputsPruned,
    })
    fs.writeFileSync(heartbeatPath, payload)
  } catch (e) {
    // Non-fatal — heartbeat is informational only
  }
}

// ============================================================================
// Utility: extractSummaryText
// ============================================================================

function extractSummaryText(response: unknown): string {
  if (!response) return "[No summary returned]"

  // Handle string responses
  if (typeof response === "string") return response

  // Handle object responses with parts array
  if (typeof response === "object" && response !== null) {
    const res = response as Record<string, unknown>

    // Try response.parts (AI SDK format)
    if (Array.isArray(res.parts)) {
      const textParts = res.parts
        .filter((p: any) => p.type === "text")
        .map((p: any) => p.text)
        .join("")
      if (textParts) return textParts
    }

    // Try response.text
    if (typeof res.text === "string") return res.text

    // Try response.choices[0].message.content (OpenAI format)
    if (Array.isArray(res.choices) && res.choices.length > 0) {
      const choice = res.choices[0] as any
      if (choice?.message?.content) return choice.message.content
    }

    // Try response.content
    if (typeof res.content === "string") return res.content
    if (Array.isArray(res.content)) {
      const textContent = res.content
        .filter((c: any) => c.type === "text")
        .map((c: any) => c.text)
        .join("")
      if (textContent) return textContent
    }
  }

  return "[Unable to extract summary text]"
}

// ============================================================================
// Utility: formatStats
// ============================================================================

function formatStats(stats: PrunerStats): string {
  return [
    "**sigil-pruner Statistics**",
    "",
    `Tool outputs pruned:     ${stats.toolOutputsPruned}`,
    `Tool inputs pruned:      ${stats.toolInputsPruned}`,
    `Messages compressed:     ${stats.messagesCompressed}`,
    `Estimated tokens saved:  ${stats.estimatedTokensSaved}`,
  ].join("\n")
}
