package com.opencode.acp.intelligence.context

import io.kotest.matchers.shouldBe
import io.kotest.matchers.ints.shouldBeGreaterThan
import io.kotest.matchers.ints.shouldBeLessThan
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain
import org.junit.jupiter.api.Test

/**
 * Unit tests for [formatRepoStructureMarkdown] — the pure markdown formatter
 * extracted from [ContextGenerator].
 */
class ContextGeneratorTest {

    private fun sampleData(
        projectName: String = "my-project",
        modules: List<String> = listOf("app", "core"),
        techStack: List<String> = listOf("Gradle", "Kotlin"),
        keySymbols: List<SymbolEntry> = listOf(
            SymbolEntry("Foo", "src/Foo.kt", "com.example.Foo", "class"),
            SymbolEntry("Bar", "src/Bar.kt", "com.example.Bar", "class"),
        ),
        sourceFileCounts: Map<String, Int> = mapOf("kt" to 10, "java" to 5),
    ) = RepoData(
        projectName = projectName,
        basePath = "/tmp/my-project",
        modules = modules,
        techStack = techStack,
        keySymbols = keySymbols,
        sourceFileCounts = sourceFileCounts,
    )

    @Test
    fun `renders the project name in the title`() {
        val md = formatRepoStructureMarkdown(sampleData(projectName = "acme"))
        md shouldContain "# Repository Structure: acme"
    }

    @Test
    fun `includes the auto-generated banner`() {
        val md = formatRepoStructureMarkdown(sampleData())
        md shouldContain "Auto-generated by Sigil's `/generate-context` command. Do not edit manually."
    }

    @Test
    fun `lists tech stack items as bullets`() {
        val md = formatRepoStructureMarkdown(sampleData(techStack = listOf("Gradle", "Kotlin", "Java")))
        md shouldContain "- Gradle"
        md shouldContain "- Kotlin"
        md shouldContain "- Java"
    }

    @Test
    fun `renders not detected when tech stack is empty`() {
        val md = formatRepoStructureMarkdown(sampleData(techStack = emptyList()))
        md shouldContain "- (not detected)"
    }

    @Test
    fun `lists modules as bullets`() {
        val md = formatRepoStructureMarkdown(sampleData(modules = listOf("app", "core", "web")))
        md shouldContain "- app"
        md shouldContain "- core"
        md shouldContain "- web"
    }

    @Test
    fun `renders single module placeholder when modules is empty`() {
        val md = formatRepoStructureMarkdown(sampleData(modules = emptyList()))
        md shouldContain "- (single module)"
    }

    @Test
    fun `renders source files table with header`() {
        val md = formatRepoStructureMarkdown(sampleData())
        md shouldContain "| Extension | Count |"
        md shouldContain "|-----------|-------|"
        md shouldContain "| .kt | 10 |"
        md shouldContain "| .java | 5 |"
    }

    @Test
    fun `renders key symbols table with header`() {
        val md = formatRepoStructureMarkdown(sampleData())
        md shouldContain "| Name | File | Qualified Name | Kind |"
        md shouldContain "|------|------|----------------|------|"
    }

    @Test
    fun `renders each key symbol row with backticked values`() {
        val md = formatRepoStructureMarkdown(sampleData())
        md shouldContain "| `Foo` | `src/Foo.kt` | `com.example.Foo` | class |"
        md shouldContain "| `Bar` | `src/Bar.kt` | `com.example.Bar` | class |"
    }

    @Test
    fun `renders empty key symbols table when none provided`() {
        val md = formatRepoStructureMarkdown(sampleData(keySymbols = emptyList()))
        md shouldContain "| Name | File | Qualified Name | Kind |"
        md shouldContain "| (no symbols found) | | | |"
    }

    @Test
    fun `includes conventions section`() {
        val md = formatRepoStructureMarkdown(sampleData())
        md shouldContain "## Conventions"
        md shouldContain "This file is included in every prompt via `opencode.json` `instructions` glob."
        md shouldContain "Regenerate with `/generate-context` after major structural changes."
    }

    @Test
    fun `section order is tech stack then modules then source files then key symbols then conventions`() {
        val md = formatRepoStructureMarkdown(sampleData())
        val techIdx = md.indexOf("## Tech Stack")
        val modulesIdx = md.indexOf("## Modules")
        val sourceIdx = md.indexOf("## Source Files")
        val symbolsIdx = md.indexOf("## Key Symbols")
        val convIdx = md.indexOf("## Conventions")
        techIdx shouldBeGreaterThan 0
        techIdx shouldBeLessThan modulesIdx
        modulesIdx shouldBeLessThan sourceIdx
        sourceIdx shouldBeLessThan symbolsIdx
        symbolsIdx shouldBeLessThan convIdx
    }

    @Test
    fun `handles symbol entry with unknown file`() {
        val data = sampleData(keySymbols = listOf(SymbolEntry("Baz", "<unknown>", "com.example.Baz", "class")))
        val md = formatRepoStructureMarkdown(data)
        md shouldContain "| `Baz` | `<unknown>` | `com.example.Baz` | class |"
    }

    @Test
    fun `handles special characters in symbol names`() {
        val data = sampleData(keySymbols = listOf(SymbolEntry("My_Class", "src/a.kt", "com.example.My_Class", "class")))
        val md = formatRepoStructureMarkdown(data)
        md shouldContain "| `My_Class` | `src/a.kt` | `com.example.My_Class` | class |"
    }
}