package com.opencode.acp.chat.ui.theme

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.remember
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.shape.CircleShape
import org.jetbrains.jewel.bridge.retrieveColorOrUnspecified

// ── CompositionLocal ────────────────────────────────────────────────────────

val LocalChatTheme = staticCompositionLocalOf<ChatThemeData> {
    error("No ChatThemeData provided — wrap your composable tree in ChatTheme {}")
}

/**
 * Provides [ChatThemeData] to the composition tree.
 * Reads semantic colors from IntelliJ's UIManager via [retrieveColorOrUnspecified].
 * Must be called inside a Compose context (e.g., inside a JewelTheme).
 */
@Composable
fun ChatTheme(content: @Composable () -> Unit) {
    val themeData = rememberChatThemeData()
    CompositionLocalProvider(LocalChatTheme provides themeData) {
        content()
    }
}

/**
 * Convenience accessor: `ChatTheme.colors.surface.primary`
 */
object ChatTheme {
    val colors: ChatThemeData.Colors @Composable get() = LocalChatTheme.current.colors
    val dims: ChatThemeData.Dims @Composable get() = LocalChatTheme.current.dims
    val fonts: ChatThemeData.Fonts @Composable get() = LocalChatTheme.current.fonts
    val fontWeights: ChatThemeData.FontWeights @Composable get() = LocalChatTheme.current.fontWeights
    val shapes: ChatThemeData.Shapes @Composable get() = LocalChatTheme.current.shapes
    val animations: ChatThemeData.Animations @Composable get() = LocalChatTheme.current.animations
}

/**
 * Creates [ChatThemeData] by reading semantic colors from IntelliJ's UIManager.
 * Called once by [ChatTheme] composable. Hardcoded values for chat-specific accents.
 * Wrapped in [remember] to avoid recreating the object every recomposition.
 */
@Composable
private fun rememberChatThemeData(): ChatThemeData {
    // Semantic colors — read from IDE theme
    val panelBg = retrieveColorOrUnspecified("Panel.background")
    val panelFg = retrieveColorOrUnspecified("Panel.foreground")
    val borderColor = retrieveColorOrUnspecified("Component.borderColor")
    val selectionBg = retrieveColorOrUnspecified("List.selectionBackground")
    val selectionFg = retrieveColorOrUnspecified("List.selectionForeground")
    val hoverBg = retrieveColorOrUnspecified("MenuItem.selectionBackground")
    val linkColor = retrieveColorOrUnspecified("Link.activeForeground")
    val errorColor = retrieveColorOrUnspecified("Component.errorFocusColor")
    val disabledFg = retrieveColorOrUnspecified("Label.disabledForeground")

    return remember(panelBg, panelFg, borderColor, selectionBg, selectionFg, hoverBg, linkColor, errorColor, disabledFg) {
        ChatThemeData(
        colors = ChatThemeData.Colors(
            surface = ChatThemeData.SurfaceColors(
                primary = panelBg,
                secondary = panelBg.copy(red = panelBg.red * 0.85f, green = panelBg.green * 0.85f, blue = panelBg.blue * 0.85f),
                card = panelBg.copy(red = panelBg.red * 0.9f, green = panelBg.green * 0.9f, blue = panelBg.blue * 0.9f),
                dark = panelBg.copy(red = panelBg.red * 0.75f, green = panelBg.green * 0.75f, blue = panelBg.blue * 0.75f),
                elevated = hoverBg,
                tableHeader = panelBg.copy(red = panelBg.red * 0.82f, green = panelBg.green * 0.82f, blue = panelBg.blue * 0.82f),
            ),
            text = ChatThemeData.TextColors(
                primary = panelFg,
                secondary = panelFg.copy(alpha = 0.85f),
                muted = panelFg.copy(alpha = 0.5f),
                disabled = disabledFg,
                inverse = Color.White,
                link = linkColor,
                error = errorColor,
            ),
            border = ChatThemeData.BorderColors(
                default = borderColor,
                subtle = borderColor.copy(alpha = 0.6f),
                accent = borderColor.copy(alpha = 0.8f),
                selectionBg = selectionBg,
                selectionFg = selectionFg,
            ),
            accent = ChatThemeData.AccentColors(
                green = Color(0xFF6BBE50),
                greenLight = Color(0xFF4EAF4E),
                blue = Color(0xFF3574F0),
                red = Color(0xFFE5534B),
                yellow = Color(0xFFE5A617),
                infoBlue = Color(0xFF589DF6),
                contextGreen = Color(0xFF6BBE50),
                contextYellow = Color(0xFFE5A617),
                contextRed = Color(0xFFE5534B),
                contextUnknown = Color(0xFF808080),
                codeAdded = Color(0xFF7EE787),
                codeDeleted = Color(0xFFFF7B72),
                codeModified = Color(0xFFF0C674),
                inlineCodeBackground = Color.Transparent,
                blockQuoteLine = Color(0xFF3E3E3E),
                blockQuoteText = Color(0xFF9E9E9E),
                pillContainerBg = Color(0x0CFFFFFF),
                overlaySemiTransparent = Color(0x88000000),
                highlightBlueAlpha = Color(0x182196F3),
                highlightBlueBorder = Color(0x402196F3),
                bannerErrorBg = Color(0x1ADB4437),
                bannerErrorBorder = Color(0x40DB4437),
                bannerInfoBg = Color(0x1A589DF6),
                bannerInfoBorder = Color(0x40589DF6),
                userBubbleBg = Color(0xFF3574F0).copy(alpha = 0.12f),
                userAvatarBorder = Color(0xFF3574F0),
                userAvatarFill = Color(0xFF5E9AFF),
                permissionBorder = Color(0x40808080),
                permissionBg = Color(0x10808080),
            ),
            provider = ChatThemeData.ProviderColors(
                anthropic = Color(0xFFCC785C),
                openAI = Color(0xFF10A37F),
                deepSeek = Color(0xFF4D6BFE),
                google = Color(0xFF4285F4),
                ollama = Color(0xFFCCCCCC),
                mistral = Color(0xFFDDA63A),
                cohere = Color(0xFF39D98A),
                groq = Color(0xFFF55036),
                together = Color(0xFF6366F1),
                fireworks = Color(0xFFFF6B35),
                nvidia = Color(0xFF76B900),
                openRouter = Color(0xFF8B5CF6),
                gitHubCopilot = Color(0xFFCCCCCC),
                xAI = Color(0xFFCCCCCC),
                alibaba = Color(0xFFFF6A00),
                miniMax = Color(0xFF6366F1),
                moonshot = Color(0xFFCCCCCC),
                stepFun = Color(0xFFCCCCCC),
                zhipu = Color(0xFF4D6BFE),
                kimi = Color(0xFFCCCCCC),
                colorMap = mapOf(
                    "anthropic" to Color(0xFFCC785C),
                    "openai" to Color(0xFF10A37F),
                    "deepseek" to Color(0xFF4D6BFE),
                    "google" to Color(0xFF4285F4),
                    "ollama-cloud" to Color(0xFFCCCCCC),
                    "mistral" to Color(0xFFDDA63A),
                    "cohere" to Color(0xFF39D98A),
                    "groq" to Color(0xFFF55036),
                    "togetherai" to Color(0xFF6366F1),
                    "fireworks-ai" to Color(0xFFFF6B35),
                    "nvidia" to Color(0xFF76B900),
                    "openrouter" to Color(0xFF8B5CF6),
                    "github-copilot" to Color(0xFFCCCCCC),
                    "xai" to Color(0xFFCCCCCC),
                    "alibaba" to Color(0xFFFF6A00),
                    "minimax" to Color(0xFF6366F1),
                    "moonshotai" to Color(0xFFCCCCCC),
                    "stepfun" to Color(0xFFCCCCCC),
                    "zhipuai" to Color(0xFF4D6BFE),
                    "kimi-for-coding" to Color(0xFFCCCCCC),
                ),
            ),
            file = ChatThemeData.FileColors(
                kotlin = Color(0xFFA97BFF),
                java = Color(0xFFED8B00),
                javaScript = Color(0xFFF7DF1E),
                typeScript = Color(0xFF3178C6),
                python = Color(0xFF3776AB),
                ruby = Color(0xFFCC342D),
                go = Color(0xFF00ADD8),
                rust = Color(0xFFCE422B),
                html = Color(0xFFE44D26),
                css = Color(0xFF264DE4),
                xml = Color(0xFF0060AC),
                json = Color(0xFFBBBBBB),
                yaml = Color(0xFFCB171E),
                markdown = Color(0xFF519ABA),
                sql = Color(0xFFE38C00),
                shell = Color(0xFF4EAA25),
            ),
            tool = ChatThemeData.ToolColors(
                execute = Color(0xFF3574F0),
                edit = Color(0xFF7EE787),
                read = Color(0xFFBBBBBB),
                search = Color(0xFFF0C674),
                delete = Color(0xFFFF7B72),
                move = Color(0xFFBBBBBB),
                fetch = Color(0xFFF0C674),
                think = Color(0xFF9E9E9E),
                switchMode = Color(0xFF9E9E9E),
                other = Color(0xFF9E9E9E),
            ),
            component = ChatThemeData.ComponentColors(
                sidebarShimmerCreating = Color(0xFFFFC107),
                sidebarShimmerStreaming = Color(0xFF4CAF50),
                splashConnected = Color(0xFF4CAF50),
                splashError = Color(0xFFF44336),
                splashRetry = Color(0xFFFF9800),
                taskAccent = Color(0xFF7EE787),
                taskRunning = Color(0xFF808080),
                taskCompleted = Color(0xFFCCCCCC),
                taskFailed = Color(0xFFFF7B72),
                taskPending = Color(0xFF808080),
                retryBg = Color(0xFF5C4A00),
                retryText = Color(0xFFFFD666),
                retryErrorDetail = Color(0xFFCCAA44),
                selectionCheckboxFill = Color(0xFF2196F3),
                selectionCheckboxBorder = Color.Gray,
                selectionCustomBullet = Color(0xFF4CAF50),
                interruptedDivider = Color(0xFF444444),
                tableHeaderText = Color(0xFF6BBE50),
                tableCellText = Color(0xFFD4D4D4),
                tableSeparator = Color(0xFF3E3E3E),
                tableHeaderBg = Color(0xFF2A2A2A),
                tableHoverBg = Color(0xFF252525),
                tableBorder = Color(0xFF3E3E3E),
                tableContainerBg = Color(0xFF1E1E1E),
                glowTransparent = Color.Transparent,
                glowStart = Color(0xFF4A9EFF).copy(alpha = 0.15f),
                glowPeak = Color(0xFF4A9EFF).copy(alpha = 0.45f),
                glowHot = Color(0xFF00D4FF).copy(alpha = 0.85f),
                inputBg = Color(0xFF2B2B2B),
                inputBorder = Color(0xFF3E3E3E),
                inputCursor = Color.White,
                inputText = Color(0xFFCCCCCC),
                inputPlaceholder = Color(0xFF808080),
                dragActiveBg = Color(0xFF2E3A2E),
                attachmentBg = Color(0xFF3E3E3E),
                attachmentRemoveIcon = Color(0xFFBBBBBB),
                attachmentImageOverlay = Color(0xFF555555),
                attachmentImageRemove = Color(0xFFCCCCCC),
                attachmentFileSize = Color(0xFF808080),
                contextPanelLabel = Color(0xFF999999),
                contextPanelValue = Color(0xFFDDDDDD),
                contextPanelSeparator = Color(0xFF3E3E3E),
                contextProgressBarBg = Color(0xFF3C3C3C),
                indicatorBg = Color(0xFF3C3C3C),
                tooltipBg = Color(0xFF2B2B2B),
                tooltipBorder = Color(0xFF4A4A4A),
                tooltipText = Color(0xFFCCCCCC),
                tooltipMuted = Color(0xFF999999),
                codeCopyIcon = Color(0xFF6BBE50),
                codeLanguageLabel = Color(0xFFBBBBBB),
                todoBg = Color(0xFF252525),
                todoHeader = Color(0xFF808080),
                todoPending = Color(0xFF808080),
                todoInProgress = Color(0xFFE5A617),
                todoCompleted = Color(0xFF6BBE50),
                todoCancelled = Color(0xFF666666),
                todoAccent = Color(0xFF3574F0),
                todoActiveText = Color(0xFFDDDDDD),
                compactionText = Color(0xFF7EBF7E),
                compactionIcon = Color(0xFF7EBF7E),
                selectorHoverTint = Color(0xFF3574F0),
                starGold = Color(0xFFE5C100),
                starMuted = Color(0xFF606060),
                selectedRowBg = Color(0xFF2D4F6D),
                thinkingText = Color.Gray,
                thinkingChevron = Color(0xFF9E9E9E),
                mimeText = Color(0xFF7E7E7E),
                reviewAddedLabel = Color(0xFF7CB342),
                hoverBg = hoverBg,
                compactionBg = Color(0xFF1A2A1A),
                paletteHoverBg = Color(0xFF2E3A2E),
                capabilityVision = Color(0xFF4285F4),
                splashBg = Color(0xFF1E1E1E),
            ),
        ),
        dims = ChatThemeData.Dims(
            sidebarWidth = 260.dp,
            sidebarContextWidth = 320.dp,
            sidebarReviewWidth = 260.dp,
            contextIndicatorSize = 28.dp,
            contextRingStroke = 2.dp,
            contextRingGap = 2.dp,
            contextTooltipWidth = 240.dp,
            contextTooltipPadding = 8.dp,
            contextErrorBadgeBorder = 1.dp,
            inputOuterPaddingH = 12.dp,
            inputOuterPaddingV = 8.dp,
            inputCornerRadius = 12.dp,
            inputMinHeight = 56.dp,
            inputMaxHeight = 156.dp,
            inputLineHeight = 20.dp,
            inputContentPaddingH = 12.dp,
            inputContentPaddingV = 8.dp,
            inputDragBorderWidth = 2.dp,
            inputDefaultBorderWidth = 1.dp,
            actionButtonSize = 28.dp,
            actionButtonCornerRadius = 6.dp,
            actionIconSize = 16.dp,
            stopIconSize = 12.dp,
            attachmentThumbnailSize = 48.dp,
            attachmentThumbnailCornerRadius = 6.dp,
            attachmentChipPaddingH = 6.dp,
            attachmentChipPaddingV = 4.dp,
            attachmentFileIconSize = 14.dp,
            attachmentImageRemoveSize = 16.dp,
            attachmentImageRemoveBadge = 10.dp,
            attachmentFileRemoveBadge = 10.dp,
            modelPickerButtonSize = 32.dp,
            modelPickerPanelWidthMin = 140.dp,
            modelPickerPanelWidthMax = 240.dp,
            modelPickerPanelMaxHeight = 320.dp,
            modelPickerPanelCornerRadius = 8.dp,
            modelPickerRowHeight = 32.dp,
            selectorSize = 28.dp,
            selectorCornerRadius = 6.dp,
            messageBubbleCornerRadius = 8.dp,
            messagePaddingH = 12.dp,
            messagePaddingV = 4.dp,
            userAvatarSize = 28.dp,
            codeBlockCornerRadius = 8.dp,
            codeHeaderPaddingH = 12.dp,
            codeHeaderPaddingV = 4.dp,
            codeCopyIconSize = 14.dp,
            codeLanguageIconSize = 16.dp,
            toolPillCornerRadius = 8.dp,
            toolAccentStripWidth = 3.dp,
            toolAccentStripHeight = 40.dp,
            toolAccentStripCornerRadius = 1.5.dp,
            sessionRowCornerRadius = 6.dp,
            sessionRowPaddingH = 10.dp,
            sessionRowPaddingV = 8.dp,
            sessionChevronSize = 16.dp,
            sessionIconSize = 14.dp,
            sessionIndentPerLevel = 16.dp,
            contextProgressBarHeight = 18.dp,
            contextProgressBarCornerRadius = 4.dp,
            todoCornerRadius = 8.dp,
            todoPaddingH = 12.dp,
            todoPaddingV = 6.dp,
            todoStatusIconSize = 12.dp,
            todoChevronSize = 12.dp,
            paletteCornerRadius = 8.dp,
            paletteMaxWidth = 300.dp,
            paletteRowCornerRadius = 4.dp,
            permissionCornerRadius = 4.dp,
            permissionBorderWidth = 1.dp,
            permissionPaddingH = 8.dp,
            permissionPaddingV = 4.dp,
            selectionCornerRadius = 8.dp,
            selectionBorderWidth = 1.dp,
            selectionCheckboxSize = 18.dp,
            selectionCheckboxCornerRadius = 3.dp,
            selectionRowCornerRadius = 4.dp,
            selectionMaxHeight = 240.dp,
            bannerBorderWidth = 1.dp,
            bannerCornerRadius = 4.dp,
            bannerPaddingH = 8.dp,
            bannerPaddingV = 4.dp,
            bannerIconSize = 16.dp,
            splashLogoSize = 64.dp,
            splashIndicatorSize = 16.dp,
            splashSettingsDotSize = 12.dp,
            splashButtonCornerRadius = 8.dp,
            thinkingSpinnerSize = 16.dp,
            thinkingStreamingSpinnerSize = 14.dp,
            reviewFileIconSize = 16.dp,
            reviewOpenFileIconSize = 18.dp,
            overlayCornerRadius = 8.dp,
        ),
        fonts = ChatThemeData.Fonts(
            inputText = 13.sp,
            inputPlaceholder = 13.sp,
            attachmentFileName = 12.sp,
            attachmentFileSize = 11.sp,
            messageBody = 13.sp,
            messageOrderedListItem = 14.sp,
            messagePatchFileCount = 12.sp,
            messagePatchFileName = 11.sp,
            messageFileName = 12.sp,
            messageFileMime = 10.sp,
            messageInterrupted = 12.sp,
            messageAgentBadge = 11.sp,
            messageStepFinish = 11.sp,
            messageError = 11.sp,
            codeBody = 13.sp,
            codeLanguageLabel = 11.sp,
            codeCopiedLabel = 12.sp,
            toolKindLabel = 13.sp,
            toolFileName = 12.sp,
            toolLineDelta = 12.sp,
            toolTaskDescription = 12.sp,
            toolTaskStatus = 11.sp,
            thinkingLabel = 13.sp,
            thinkingChevron = 16.sp,
            contextPercent = 10.sp,
            contextErrorBadge = 8.sp,
            contextTooltipLabel = 10.sp,
            contextTooltipValue = 11.sp,
            contextTooltipSub = 9.sp,
            contextPanelTitle = 12.sp,
            contextSectionHeader = 12.sp,
            contextDetailLabel = 11.sp,
            contextDetailValue = 11.sp,
            contextProgressBarPercent = 7.sp,
            sessionTitle = 12.sp,
            sessionFooter = 11.sp,
            sessionDialogTitle = 14.sp,
            sessionDialogBody = 12.sp,
            paletteCommand = 12.sp,
            paletteDescription = 11.sp,
            paletteEmpty = 12.sp,
            pickerModelName = 12.sp,
            pickerContextWindow = 10.sp,
            pickerProviderLetter = 9.sp,
            pickerSectionHeader = 11.sp,
            pickerSearchPlaceholder = 12.sp,
            pickerFooter = 10.sp,
            todoHeader = 11.sp,
            todoCount = 10.sp,
            todoContent = 11.sp,
            todoMoreHint = 10.sp,
            selectorChip = 12.sp,
            selectorItem = 12.sp,
            bannerText = 13.sp,
            splashTitle = 24.sp,
            splashStatus = 14.sp,
            splashSettingsLabel = 12.sp,
            splashError = 14.sp,
            tableCell = 13.sp,
            attachMenuFileName = 12.sp,
            attachMenuFilePath = 10.sp,
            attachMenuSectionLabel = 11.sp,
            attachMenuSearchPlaceholder = 12.sp,
            reviewFileName = 12.sp,
            reviewStatusLabel = 10.sp,
            reviewFilePath = 10.sp,
            reviewLineDelta = 11.sp,
            reviewLoading = 12.sp,
            reviewEmpty = 12.sp,
            reviewError = 12.sp,
            permissionDescription = 12.sp,
            selectionQuestion = 14.sp,
            selectionSubtitle = 12.sp,
            selectionCustomBullet = 16.sp,
            selectionCheckmark = 12.sp,
            selectionOptionTitle = 13.sp,
            selectionOptionDescription = 11.sp,
        ),
        fontWeights = ChatThemeData.FontWeights(
            sectionHeader = FontWeight.Bold,
            badge = FontWeight.Medium,
            semibold = FontWeight.SemiBold,
            detailLabel = FontWeight.SemiBold,
            detailValue = FontWeight.Normal,
            contextPercent = FontWeight.Bold,
            todoHeader = FontWeight.SemiBold,
            selectionQuestion = FontWeight.Bold,
            selectionCheckmark = FontWeight.Bold,
            selectionOptionTitle = FontWeight.Medium,
            commandName = FontWeight.SemiBold,
            toolKindLabel = FontWeight.Bold,
            toolLineDelta = FontWeight.Medium,
            bannerText = FontWeight.Medium,
            splashTitle = FontWeight.Bold,
            splashError = FontWeight.Medium,
            tableHeader = FontWeight.Bold,
            sessionTitleSelected = FontWeight.Medium,
            sessionTitleUnselected = FontWeight.Normal,
        ),
        shapes = ChatThemeData.Shapes(
            inputCornerRadius = RoundedCornerShape(12.dp),
            attachmentCornerRadius = RoundedCornerShape(6.dp),
            actionButtonCornerRadius = RoundedCornerShape(6.dp),
            messageBubbleCornerRadius = RoundedCornerShape(8.dp),
            codeBlockCornerRadius = RoundedCornerShape(8.dp),
            toolPillCornerRadius = RoundedCornerShape(8.dp),
            toolAccentCornerRadius = RoundedCornerShape(1.5.dp),
            sessionRowCornerRadius = RoundedCornerShape(6.dp),
            contextIndicatorShape = CircleShape,
            contextErrorBadgeShape = CircleShape,
            contextTooltipCornerRadius = RoundedCornerShape(6.dp),
            contextProgressBarCornerRadius = RoundedCornerShape(4.dp),
            todoCornerRadius = RoundedCornerShape(8.dp),
            paletteCornerRadius = RoundedCornerShape(8.dp),
            paletteRowCornerRadius = RoundedCornerShape(4.dp),
            permissionCornerRadius = RoundedCornerShape(4.dp),
            selectionCornerRadius = RoundedCornerShape(8.dp),
            selectionCheckboxCornerRadius = RoundedCornerShape(3.dp),
            selectionRowCornerRadius = RoundedCornerShape(4.dp),
            bannerCornerRadius = RoundedCornerShape(4.dp),
            splashButtonCornerRadius = RoundedCornerShape(8.dp),
            splashSettingsCornerRadius = RoundedCornerShape(2.dp),
            chipCornerRadius = RoundedCornerShape(6.dp),
            pickerCornerRadius = RoundedCornerShape(8.dp),
            pickerRowCornerRadius = RoundedCornerShape(4.dp),
            modelPickerButtonShape = CircleShape,
            fileChangeRowCornerRadius = RoundedCornerShape(4.dp),
            errorBadgeCornerRadius = RoundedCornerShape(4.dp),
            avatarShape = CircleShape,
            imageRemoveBadgeShape = CircleShape,
            fileRemoveBadgeShape = CircleShape,
            searchIconShape = CircleShape,
            splashSettingsIndicatorShape = RoundedCornerShape(2.dp),
            sidebarLeftCornerRadius = RoundedCornerShape(topStart = 12.dp, bottomStart = 12.dp),
            overlayCornerRadius = RoundedCornerShape(8.dp),
            dialogCornerRadius = RoundedCornerShape(8.dp),
            retryPillCornerRadius = RoundedCornerShape(4.dp),
            attachMenuCornerRadius = RoundedCornerShape(8.dp),
            attachFileRowCornerRadius = RoundedCornerShape(4.dp),
            tableCornerRadius = RoundedCornerShape(8.dp),
        ),
        animations = ChatThemeData.Animations(
            glowPulseMs = 2500,
            contextPulseMs = 800,
            shimmerSweepMs = 1500,
            chipHoverMs = 150,
            thinkingIndicatorDelayMs = 300L,
        ),
    )
    }
}
