package com.opencode.acp.intelligence

import io.github.oshai.kotlinlogging.KotlinLogging
import java.nio.file.Files
import java.nio.file.StandardCopyOption

private val logger = KotlinLogging.logger {}

/**
 * Extracts bundled skill markdown files from JAR resources to `.opencode/skills/`
 * and bundled context files to `.opencode/context/` before the OpenCode server
 * launches.
 *
 * - **Skills** (`.opencode/skills/`): discovered by the server as invocable
 *   `$skill` commands. NEVER overwritten — the user may have customized them.
 * - **Context** (`.opencode/context/`): always-in-context instruction files
 *   loaded via the `instructions` glob in `opencode.json`. ALWAYS overwritten
 *   on each launch — these are auto-generated reference docs that must reflect
 *   the current plugin/tool definitions.
 *
 * Mirrors the [com.opencode.acp.chat.processor.PrunerResourceExtractor] pattern:
 * extract from JAR resources via temp file + atomic move.
 *
 * @param projectBasePath The project root directory (where `.opencode/` lives).
 */
class SkillResourceExtractor(private val projectBasePath: java.nio.file.Path) {

    /**
     * Bundled skills to extract. Each entry maps a JAR resource path to a
     * target relative path under `.opencode/skills/`.
     * Never overwritten — user may have customized.
     */
    private val bundledSkills = listOf(
        "/opencode-skills/psi-code-intelligence/SKILL.md" to "psi-code-intelligence/SKILL.md",
    )

    /**
     * Bundled context files to extract. Each entry maps a JAR resource path to
     * a target relative path under `.opencode/context/`.
     * NEVER overwritten — these are FALLBACK seeds only. The authoritative
     * `intellij-mcp-tools.md` is generated by [com.opencode.acp.intelligence.context.McpToolsDocGenerator]
     * via `/generate-context` from the live tool registry, and overwriting it
     * here would clobber the IDE-aware generated version with the static
     * generic one on every server launch.
     */
    private val bundledContextFiles = listOf(
        "/opencode-context/intellij-mcp-tools.md" to "intellij-mcp-tools.md",
    )

    /**
     * Extract all bundled skills to `.opencode/skills/` and context files to
     * `.opencode/context/`.
     *
     * Skills are only extracted if they don't already exist (never overwrite
     * user-modified files). Context files are always overwritten (they are
     * auto-generated reference docs that must reflect current tool definitions).
     *
     * @return true if all extractions succeeded (or were already present).
     */
    fun extractAll(): Boolean {
        val skillsDir = projectBasePath.resolve(".opencode").resolve("skills")
        val contextDir = projectBasePath.resolve(".opencode").resolve("context")

        var allOk = true

        // Clean up orphaned temp files from previous failed extractions/writes.
        // Covers all plugin-generated temp-file prefixes: skill.* (this extractor),
        // repo-structure.* and intellij-mcp-tools.* (ContextFileWriter),
        // opencode.json.* (McpConfigWriter), and .atomic-* (AtomicFileWriter).
        for (dir in listOf(skillsDir, contextDir)) {
            try {
                if (Files.exists(dir)) {
                    Files.list(dir).use { stream ->
                        stream.filter { f ->
                            val name = f.fileName.toString()
                            name.endsWith(".tmp") && (
                                    name.startsWith("skill.") ||
                                            name.startsWith("repo-structure.") ||
                                            name.startsWith("intellij-mcp-tools.") ||
                                            name.startsWith("opencode.json.") ||
                                            name.startsWith(".atomic-")
                                    )
                        }
                            .forEach {
                                try {
                                    Files.deleteIfExists(it)
                                } catch (_: Exception) {
                                }
                            }
                    }
                }
            } catch (_: Exception) {
                // Best-effort cleanup — don't fail if cleanup doesn't work
            }
        }

        // Extract skills (never overwrite)
        for ((resourcePath, targetRelative) in bundledSkills) {
            try {
                extractResource(
                    resourcePath = resourcePath,
                    target = skillsDir.resolve(targetRelative),
                    overwrite = false,
                )
            } catch (e: Exception) {
                logger.warn(e) { "[ACP] SkillResourceExtractor: failed to extract skill $resourcePath" }
                allOk = false
            }
        }

        // Extract context files as fallback seeds (never overwrite — the
        // generated version from /generate-context is authoritative).
        for ((resourcePath, targetRelative) in bundledContextFiles) {
            try {
                extractResource(
                    resourcePath = resourcePath,
                    target = contextDir.resolve(targetRelative),
                    overwrite = false,
                )
            } catch (e: Exception) {
                logger.warn(e) { "[ACP] SkillResourceExtractor: failed to extract context $resourcePath" }
                allOk = false
            }
        }

        return allOk
    }

    /**
     * Extract a single resource to [target].
     *
     * @param overwrite if true, always overwrite existing file (atomic temp + move).
     *                   if false, skip extraction if the target already exists.
     */
    private fun extractResource(resourcePath: String, target: java.nio.file.Path, overwrite: Boolean) {
        val resource = javaClass.getResourceAsStream(resourcePath)
        if (resource == null) {
            logger.warn { "[ACP] SkillResourceExtractor: resource not found: $resourcePath" }
            return
        }

        val resourceContent = resource.use { it.readAllBytes().decodeToString().removePrefix("\uFEFF") }

        Files.createDirectories(target.parent)

        if (!overwrite && Files.exists(target)) {
            logger.debug { "[ACP] SkillResourceExtractor: ${target.fileName} already exists (user may have customized) — skipping" }
            return
        }

        logger.info { "[ACP] SkillResourceExtractor: extracting ${target.fileName} (overwrite=$overwrite)" }

        // Atomic write via temp file + move (same pattern as McpConfigWriter/ContextFileWriter)
        val tempFile = Files.createTempFile(target.parent, "skill.", ".tmp")
        try {
            Files.writeString(tempFile, resourceContent)
            try {
                Files.move(tempFile, target, StandardCopyOption.ATOMIC_MOVE)
            } catch (e: java.nio.file.AtomicMoveNotSupportedException) {
                logger.warn { "[ACP] SkillResourceExtractor: atomic move not supported, falling back to non-atomic" }
                Files.move(tempFile, target, StandardCopyOption.REPLACE_EXISTING)
            }
        } catch (e: Exception) {
            try {
                Files.deleteIfExists(tempFile)
            } catch (_: Exception) {
            }
            throw e
        }
    }
}