package com.opencode.acp.intelligence

import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import java.nio.file.Files
import java.nio.file.Path
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

class SkillResourceExtractorTest {

    @Test
    fun `extracts bundled skills to opencode-skills dir`(@TempDir tmp: Path) {
        val extractor = SkillResourceExtractor(tmp)
        val ok = extractor.extractAll()

        ok shouldBe true
        val skillFile = tmp.resolve(".opencode/skills/psi-code-intelligence/SKILL.md")
        Files.exists(skillFile) shouldBe true
        skillFile.toFile().readText() shouldContain "#"
    }

    @Test
    fun `extracts bundled context file to opencode-context dir as fallback seed`(@TempDir tmp: Path) {
        val extractor = SkillResourceExtractor(tmp)
        val ok = extractor.extractAll()

        ok shouldBe true
        val contextFile = tmp.resolve(".opencode/context/intellij-mcp-tools.md")
        Files.exists(contextFile) shouldBe true
        val content = contextFile.toFile().readText()
        content shouldContain "IntelliJ MCP Tools"
        content shouldContain "intellij_read_file"
        content shouldContain "intellij_analyze_calls"
        content shouldContain "intellij_apply_patch"
    }

    @Test
    fun `context file is NOT overwritten on re-extraction — generated version is authoritative`(@TempDir tmp: Path) {
        // The static intellij-mcp-tools.md is a FALLBACK seed only. The authoritative
        // version is generated by McpToolsDocGenerator via /generate-context from the
        // live tool registry. Re-extraction must not clobber a generated/customized file.
        val extractor = SkillResourceExtractor(tmp)
        extractor.extractAll()

        val contextFile = tmp.resolve(".opencode/context/intellij-mcp-tools.md")
        // Simulate a generated, IDE-aware version (what /generate-context writes).
        Files.writeString(contextFile, "GENERATED IDE-AWARE CONTENT")

        // Re-extract — context files are never overwritten (fallback seed only).
        extractor.extractAll()

        contextFile.toFile().readText() shouldBe "GENERATED IDE-AWARE CONTENT"
    }

    @Test
    fun `context file is seeded when missing`(@TempDir tmp: Path) {
        // Fresh checkout: no context file exists → the static fallback seeds it.
        val extractor = SkillResourceExtractor(tmp)
        extractor.extractAll()

        val contextFile = tmp.resolve(".opencode/context/intellij-mcp-tools.md")
        Files.exists(contextFile) shouldBe true
        contextFile.toFile().readText() shouldContain "IntelliJ MCP Tools"
    }

    @Test
    fun `skills are NOT overwritten on re-extraction`(@TempDir tmp: Path) {
        val extractor = SkillResourceExtractor(tmp)
        extractor.extractAll()

        val skillFile = tmp.resolve(".opencode/skills/psi-code-intelligence/SKILL.md")
        // Modify the file (simulate user customization)
        Files.writeString(skillFile, "USER CUSTOMIZED CONTENT")

        // Re-extract — skills are never overwritten
        extractor.extractAll()

        skillFile.toFile().readText() shouldBe "USER CUSTOMIZED CONTENT"
    }
}