package com.opencode.acp.intelligence.context

import io.github.oshai.kotlinlogging.KotlinLogging
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption

private val logger = KotlinLogging.logger {}

/**
 * Writes context files to `.opencode/context/` in the project directory.
 *
 * Uses atomic write via temp file + Files.move (same pattern as McpConfigWriter.writeConfig).
 */
class ContextFileWriter(private val projectBasePath: Path) {

    /**
     * Write the repo-structure markdown to `.opencode/context/repo-structure.md`.
     *
     * @param content The markdown content.
     * @return true if written successfully, false on error.
     */
    fun writeRepoStructure(content: String): Boolean {
        return try {
            val contextDir = projectBasePath.resolve(".opencode").resolve("context")
            Files.createDirectories(contextDir)
            cleanupOrphanTemps(contextDir, "repo-structure.")
            val targetFile = contextDir.resolve("repo-structure.md")
            val tempFile = Files.createTempFile(contextDir, "repo-structure.", ".tmp")
            try {
                Files.writeString(tempFile, content)
                try {
                    Files.move(
                        tempFile,
                        targetFile,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE
                    )
                } catch (e: java.nio.file.AtomicMoveNotSupportedException) {
                    logger.warn { "[ACP] ContextFileWriter: atomic move not supported, falling back to non-atomic" }
                    Files.move(tempFile, targetFile, StandardCopyOption.REPLACE_EXISTING)
                }
                logger.info { "[ACP] ContextFileWriter: wrote repo-structure.md (${content.length} chars)" }
                true
            } catch (e: Exception) {
                try {
                    Files.deleteIfExists(tempFile)
                } catch (_: Exception) {
                }
                throw e
            }
        } catch (e: Exception) {
            logger.error(e) { "[ACP] ContextFileWriter: failed to write repo-structure.md" }
            false
        }
    }

    /**
     * Write the intellij-mcp-tools markdown to `.opencode/context/intellij-mcp-tools.md`.
     *
     * Generated by [McpToolsDocGenerator] from the live tool registry so the
     * reference reflects the actual MCP tools exposed by the current IDE and the
     * user's permission settings. Always overwritten (auto-generated reference).
     *
     * @param content The markdown content.
     * @return true if written successfully, false on error.
     */
    fun writeMcpToolsDoc(content: String): Boolean {
        return try {
            val contextDir = projectBasePath.resolve(".opencode").resolve("context")
            Files.createDirectories(contextDir)
            cleanupOrphanTemps(contextDir, "intellij-mcp-tools.")
            val targetFile = contextDir.resolve("intellij-mcp-tools.md")
            val tempFile = Files.createTempFile(contextDir, "intellij-mcp-tools.", ".tmp")
            try {
                Files.writeString(tempFile, content)
                try {
                    Files.move(
                        tempFile,
                        targetFile,
                        StandardCopyOption.REPLACE_EXISTING,
                        StandardCopyOption.ATOMIC_MOVE
                    )
                } catch (e: java.nio.file.AtomicMoveNotSupportedException) {
                    logger.warn { "[ACP] ContextFileWriter: atomic move not supported, falling back to non-atomic" }
                    Files.move(tempFile, targetFile, StandardCopyOption.REPLACE_EXISTING)
                }
                logger.info { "[ACP] ContextFileWriter: wrote intellij-mcp-tools.md (${content.length} chars)" }
                true
            } catch (e: Exception) {
                try {
                    Files.deleteIfExists(tempFile)
                } catch (_: Exception) {
                }
                throw e
            }
        } catch (e: Exception) {
            logger.error(e) { "[ACP] ContextFileWriter: failed to write intellij-mcp-tools.md" }
            false
        }
    }

    /**
     * Delete orphaned temp files matching `[prefix]*.tmp` in [dir].
     * Called at the start of each write method to reclaim temp files left by a
     * previous interrupted write (process killed between createTempFile and move).
     */
    private fun cleanupOrphanTemps(dir: Path, prefix: String) {
        try {
            Files.list(dir).use { stream ->
                stream.filter { f ->
                    val name = f.fileName.toString()
                    name.startsWith(prefix) && name.endsWith(".tmp")
                }.forEach {
                    try {
                        Files.deleteIfExists(it)
                    } catch (_: Exception) {
                    }
                }
            }
        } catch (_: Exception) {
            // Best-effort cleanup — don't fail the write if cleanup doesn't work.
        }
    }
}