package com.opencode.acp.intelligence.context

import com.opencode.acp.mcp.ToolInfo
import com.opencode.acp.mcp.ToolPermission
import com.opencode.acp.mcp.ToolSource

/**
 * Generates the `intellij-mcp-tools.md` context file from the live tool registry
 * snapshot and the user's permission settings.
 *
 * Unlike the old static resource (`src/main/resources/opencode-context/intellij-mcp-tools.md`),
 * this generator reflects the ACTUAL set of tools the current IDE exposes (via the
 * JetBrains MCP Server plugin) and which ones the user has enabled/disabled in
 * Settings -> Tools -> Sigil. Run via `/generate-context` alongside
 * [ContextGenerator] so both context files stay in sync with the environment.
 *
 * The JetBrains MCP Server exposes tools to OpenCode's `tools/list` with their
 * RAW names (e.g. `read_file`, `search_symbol`, `xdebug_get_stack`) — the
 * `intellij_` prefix is added by the OpenCode server only when forwarding tool
 * calls to the LLM. The [ToolRegistry] stores the raw MCP names, so this
 * generator filters by `source == MCP` (which excludes generic built-ins like
 * `read`/`edit`/`bash` that have `source == BUILTIN`) and emits the raw names.
 *
 * The generated markdown groups tools into categories (file/project ops, symbol/
 * code intelligence, call analysis, refactoring, run/debug, debugger, database,
 * VCS, project structure, threading/lock, other) plus a "Permission Status"
 * section that shows which tools are allowed/ask/denied.
 *
 * If the tool snapshot is empty (MCP not connected / no tools discovered), the
 * generator emits a minimal stub noting that no MCP tools are currently available,
 * so the context file always exists and the `instructions` glob always resolves.
 */
class McpToolsDocGenerator {

    /**
     * Generate the full markdown document.
     *
     * @param tools the live tool snapshot from [com.opencode.acp.mcp.ToolRegistry.tools].
     *   Only tools with `source == MCP` are included (generic built-in tools like
     *   `read`/`edit`/`bash` have `source == BUILTIN` and are excluded).
     * @param permissions optional map of tool name -> [ToolPermission] from
     *   [com.opencode.acp.config.settings.OpenCodeMcpSettingsState]. When non-null,
     *   a "Permission Status" section is emitted showing allow/ask/deny per tool.
     *   When null, the permission section is omitted.
     * @return the markdown content for `.opencode/context/intellij-mcp-tools.md`.
     */
    fun generate(
        tools: List<ToolInfo>,
        permissions: Map<String, ToolPermission>? = null,
    ): String {
        val mcpTools = tools
            .filter { it.source == ToolSource.MCP }
            .sortedBy { it.name }

        val sb = StringBuilder()
        sb.appendLine("# IntelliJ MCP Tools — Parameter Reference")
        sb.appendLine()
        sb.appendLine("> Auto-generated by `/generate-context` from the live tool registry.")
        sb.appendLine("> Reflects the MCP tools exposed by the current IDE and the user's")
        sb.appendLine("> permission settings (Settings -> Tools -> Sigil). Regenerate after")
        sb.appendLine("> enabling/disabling MCP servers or changing tool permissions.")
        sb.appendLine()
        sb.appendLine("> NOTE: The OpenCode server exposes these tools to the LLM with an")
        sb.appendLine("> `intellij_` prefix (e.g. `intellij_read_file`). The names below are the")
        sb.appendLine("> raw MCP names from `tools/list`; the LLM calls them as `intellij_<name>`.")
        sb.appendLine()

        if (mcpTools.isEmpty()) {
            sb.appendLine("## No MCP tools available")
            sb.appendLine()
            sb.appendLine("No MCP tools are currently registered. This usually means:")
            sb.appendLine()
            sb.appendLine("- The IntelliJ MCP Server is not enabled (Settings -> Tools -> MCP Server), or")
            sb.appendLine("- The MCP server URL is not configured in Settings -> Tools -> Sigil, or")
            sb.appendLine("- Tool discovery has not run yet (connect to the OpenCode server).")
            sb.appendLine()
            sb.appendLine("Once MCP tools are discovered, re-run `/generate-context` to regenerate this file.")
            sb.appendLine()
            return sb.toString()
        }

        sb.appendLine("## Critical parameter rules")
        sb.appendLine()
        sb.appendLine("- **All file paths** are **project-relative** (e.g. `src/main/kotlin/Foo.kt`), NOT absolute.")
        sb.appendLine("- Pass `projectPath` (the project root) on **every** call — it disambiguates and speeds resolution.")
        sb.appendLine("- Lines/columns are **1-based**.")
        sb.appendLine("- Prefer `intellij_psi_find_symbol` / `intellij_search_symbol` (semantic) over text/grep search.")
        sb.appendLine("- Prefer `intellij_analyze_calls` (call graph) over `intellij_psi_find_references` when you need the call tree.")
        sb.appendLine("- **Never guess** a symbol's FQN — find it first with `intellij_search_symbol`, then pass the returned FQN.")
        sb.appendLine()

        // Group tools into categories by name prefix/pattern.
        val categories = categorize(mcpTools)
        for ((title, categoryTools) in categories) {
            if (categoryTools.isEmpty()) continue
            sb.appendLine("## $title")
            sb.appendLine()
            sb.appendLine("| Tool | Permission | Description |")
            sb.appendLine("|------|------------|-------------|")
            for (t in categoryTools) {
                val perm = permissions?.get(t.name)?.toActionString()
                    ?: if (t.enabled) "allow" else "deny"
                // Escape |, backtick, and newline in the description — it comes from MCP
                // tools/list (server-controlled) and could contain markdown-special chars.
                val desc = t.description.take(120).replace("|", "\\|").replace("`", "\\`").replace("\n", " ")
                val safeName = toolDisplayName(t).replace("|", "\\|").replace("`", "\\`").replace("\n", " ")
                sb.appendLine("| `${safeName}` | $perm | $desc |")
            }
            sb.appendLine()
        }

        // Permission status section (when permission data is available).
        if (permissions != null) {
            sb.appendLine("## Permission Status")
            sb.appendLine()
            sb.appendLine("Per-tool allow/ask/deny is configured in Settings -> Tools -> Sigil.")
            sb.appendLine("A disabled tool must NOT be used — see the agent's Core Principle rules.")
            sb.appendLine()
            sb.appendLine("| Tool | Permission |")
            sb.appendLine("|------|------------|")
            for (t in mcpTools) {
                val perm = permissions[t.name]?.toActionString()
                    ?: if (t.enabled) "allow" else "deny"
                val safeName = toolDisplayName(t).replace("|", "\\|").replace("`", "\\`").replace("\n", " ")
                sb.appendLine("| `${safeName}` | $perm |")
            }
            sb.appendLine()
        }

        sb.appendLine("## apply_patch (general tool)")
        sb.appendLine()
        sb.appendLine("Patch format for `intellij_apply_patch` (and the generic `apply_patch`):")
        sb.appendLine()
        sb.appendLine("```")
        sb.appendLine("*** Begin Patch")
        sb.appendLine("*** Update File: path/relative/to/project/File.kt")
        sb.appendLine("@@ path/relative/to/project/File.kt:LINE_NUMBER")
        sb.appendLine("-    old line content")
        sb.appendLine("+    new line content")
        sb.appendLine("*** End Patch")
        sb.appendLine("```")
        sb.appendLine()
        sb.appendLine("- `*** Update File:` line takes a **project-relative** path.")
        sb.appendLine("- `@@` hunk header includes the file path and **starting line number**.")
        sb.appendLine("- Use `*** Begin Patch` at the top and `*** End Patch` at the bottom.")
        sb.appendLine("- For new files use `*** Add File: path` instead of `*** Update File:`.")
        sb.appendLine("- For deletions use `*** Delete File: path`.")
        sb.appendLine()

        return sb.toString()
    }

    /**
     * Return the display name for a tool as the LLM should call it.
     *
     * The OpenCode server adds the `intellij_` prefix ONLY to tools from the
     * IntelliJ MCP Server (serverName == "intellij"). Third-party MCP server
     * tools are called by their raw name (no prefix). Emitting `intellij_` for
     * a third-party tool would mislead the LLM into calling a non-existent name.
     */
    private fun toolDisplayName(t: ToolInfo): String =
        if (t.serverName == INTELLIJ_SERVER_NAME) "intellij_${t.name}" else t.name

    /**
     * Group [tools] into the standard categories used by the legacy static file.
     * Tools that don't match any category fall into "Other".
     *
     * The tool names here are the RAW MCP names (no `intellij_` prefix); the
     * JetBrains MCP Server exposes them this way and the [ToolRegistry] stores
     * them raw. The LLM calls them as `intellij_<name>`.
     */
    private fun categorize(tools: List<ToolInfo>): List<Pair<String, List<ToolInfo>>> {
        val fileOps = tools.filter { it.name in FILE_OPS }
        val symbol = tools.filter { it.name in SYMBOL_OPS }
        val callAnalysis = tools.filter { it.name in CALL_ANALYSIS_OPS }
        val refactoring = tools.filter { it.name in REFACTORING_OPS }
        val runDebug = tools.filter { it.name in RUN_DEBUG_OPS }
        val debugger = tools.filter { it.name.startsWith("xdebug_") }
        val database = tools.filter {
            it.name.startsWith("list_database") ||
                    it.name.startsWith("create_database") ||
                    it.name.startsWith("edit_database") ||
                    it.name.startsWith("execute_sql") ||
                    it.name.startsWith("cancel_sql") ||
                    it.name.startsWith("test_database") ||
                    it.name.startsWith("preview_table") ||
                    it.name.startsWith("get_database") ||
                    it.name.startsWith("introspect_schema") ||
                    it.name.startsWith("list_schema") ||
                    it.name.startsWith("fetch_query") ||
                    it.name.startsWith("list_recent_sql")
        }
        val vcs = tools.filter { it.name in VCS_OPS }
        val projectStructure = tools.filter { it.name in PROJECT_STRUCTURE_OPS }
        val threading = tools.filter { it.name in THREADING_OPS }
        val notebook = tools.filter { it.name in NOTEBOOK_OPS }
        val known = (fileOps + symbol + callAnalysis + refactoring + runDebug + debugger +
                database + vcs + projectStructure + threading + notebook).map { it.name }.toSet()
        val other = tools.filter { it.name !in known }
        return listOf(
            "File / project operations" to fileOps,
            "Symbol / code intelligence" to symbol,
            "Call analysis (PREFER over find_references for dependency graphs)" to callAnalysis,
            "Refactoring" to refactoring,
            "Run / debug" to runDebug,
            "Debugger (intellij_xdebug_*)" to debugger,
            "Database (intellij_*_database_*)" to database,
            "VCS / git" to vcs,
            "Project structure" to projectStructure,
            "Threading / lock analysis (use sparingly — heuristic, not reliable)" to threading,
            "Notebooks" to notebook,
            "Other" to other,
        )
    }

    private companion object {
        // Raw MCP tool names (no intellij_ prefix — the server adds it for the LLM).
        // Server name for the built-in IntelliJ MCP server (matches ChatConstants.MCP_SERVER_NAME_INTELLIJ).
        const val INTELLIJ_SERVER_NAME = "intellij"
        val FILE_OPS = setOf(
            "read_file", "create_new_file", "open_file_in_editor",
            "reformat_file", "list_directory_tree", "search_file",
            "search_text", "search_regex", "get_file_problems",
            "lint_files", "build_project", "apply_patch",
        )
        val SYMBOL_OPS = setOf(
            "search_symbol", "psi_find_symbol", "get_symbol_info",
            "psi_file_structure", "psi_find_references",
            "psi_call_hierarchy", "psi_impact_analysis", "psi_repo_map",
        )
        val CALL_ANALYSIS_OPS = setOf("analyze_calls")
        val REFACTORING_OPS = setOf("rename_refactoring")
        val RUN_DEBUG_OPS = setOf(
            "get_run_configurations", "execute_run_configuration",
            "execute_terminal_command", "execute_tool",
        )
        val VCS_OPS = setOf("get_repositories", "git_status")
        val PROJECT_STRUCTURE_OPS = setOf(
            "get_project_modules", "get_project_dependencies",
            "get_all_open_file_paths",
        )
        val THREADING_OPS = setOf(
            "find_threading_requirements_usages", "find_lock_requirements_usages",
        )
        val NOTEBOOK_OPS = setOf("notebookEdit", "readNotebook", "runNotebookCell")
    }
}